#!/usr/bin/env ruby

if Dir.exist?('spec') && `git diff --cached spec` =~ /(,\s?(:focus|focus:\s?true|:focus\s?=>\s?true)|^\+?\s*(fit|xit|fcontext|xcontext|fdescribe|xdescribe).*)/
  puts "\e[31mPlease focus and remove your :focus tags before committing :)"
  exit 1
end
